-- EXAM033
SELECT ENAME, COMM, NVL(COMM, 0)
    FROM EMP;
    
-- EXAM033-2
SELECT ENAME, SAL, COMM, SAL + COMM
    FROM EMP
    WHERE JOB IN ('SALESMAN', 'ANALYST');
    
-- EXAM033-3
SELECT ENAME, SAL, COMM, NVL(COMM, 0), SAL + NVL(COMM, 0)
    FROM EMP
    WHERE JOB IN ('SALESMAN', 'ANALYST');

-- EXAM033-4
SELECT ENAME, SAL, COMM, NVL2(COMM, SAL + COMM, SAL)
    FROM EMP
    WHERE JOB IN ('SALESMAN', 'ANALYST');
    
-- EXAM034
SELECT ENAME, DEPTNO, DECODE(DEPTNO, 10, 300, 20, 400, 0) AS 보너스
    FROM EMP;

-- EXAM034-2
SELECT EMPNO, MOD(EMPNO, 2), DECODE(MOD(EMPNO, 2), 0, '짝수', 1, '홀수') AS 보너스
    FROM EMP;
    
 -- EXAM034-3
 SELECT ENAME, JOB, DECODE(JOB, 'SALESMAN', 5000, 2000) AS 보너스
    FROM EMP;
    
-- EXAM035
SELECT ENAME, JOB, SAL, CASE WHEN SAL >= 3000 THEN 500
                             WHEN SAL >= 2000 THEN 300
                             WHEN SAL >= 1000 THEN 200
                             ELSE 0 END AS BONUS
    FROM EMP
    WHERE JOB IN ('SALESMAN', 'ANALYST');
    
-- EXAM035-2
SELECT ENAME, JOB, COMM, CASE WHEN COMM IS NULL THEN 500 ELSE 0 END BONUS
    FROM EMP
    WHERE JOB IN ('SALESMAN', 'ANALYST');
    
-- EXAM035-3
SELECT ENAME, JOB, CASE WHEN JOB IN ('SALESMAN', 'ANALYST') THEN 500
                        WHEN JOB IN ('CLERK', 'MANAGER') THEN 400
                        ELSE 0 END AS 보너스
    FROM EMP;
    
-- EXAM036
SELECT MAX(SAL)
    FROM EMP;
    
-- EXAM036-2
SELECT MAX(SAL)
    FROM EMP
    WHERE JOB = 'SALESMAN';
    
-- EXAM036-3
SELECT JOB, MAX(SAL)
    FROM EMP
    WHERE JOB = 'SALESMAN';

-- EXAM036-4
SELECT JOB, MAX(SAL)
    FROM EMP
    WHERE JOB = 'SALESMAN'
    GROUP BY JOB;
    
-- EXAM036-5
SELECT DEPTNO, MAX(SAL)
    FROM EMP
    GROUP BY DEPTNO;
    
-- EXAM037
SELECT MIN(SAL)
    FROM EMP
    WHERE JOB = 'SALESMAN';

-- EXAM037-2
SELECT JOB, MIN(SAL) 최소값
    FROM EMP
    GROUP BY JOB
    ORDER BY 최소값 DESC;
    
-- EXAM037-3
SELECT MIN(SAL)
    FROM EMP
    WHERE 1 = 2;
    
-- EXAM037-4
SELECT NVL(MIN(SAL), 0)
    FROM EMP
    WHERE 1 = 2;
    
-- EXAM037-5
SELECT JOB, MIN(SAL)
    FROM EMP
    WHERE JOB != 'SALESMAN'
    GROUP BY JOB;

-- EXAM038
SELECT AVG(COMM)
    FROM EMP;

-- EXAM038-2
SELECT ROUND(AVG(NVL(COMM,0)))
    FROM EMP;
    
-- EXAM039
SELECT DEPTNO, SUM(SAL)
    FROM EMP
    GROUP BY DEPTNO;
    
-- EXAM039-2
SELECT JOB, SUM(SAL)
    FROM EMP
    GROUP BY JOB
    ORDER BY SUM(SAL) DESC;

-- EXAM39-3
SELECT JOB, SUM(SAL)
    FROM EMP
    WHERE SUM(SAL) >= 4000
    GROUP BY JOB;
    
-- EXAM39-4
SELECT JOB, SUM(SAL)
    FROM EMP
    GROUP BY JOB
    HAVING SUM(SAL) >= 4000;

-- EXAM39-5
SELECT JOB, SUM(SAL)
    FROM EMP
    WHERE JOB != 'SALESMAN'
    GROUP BY JOB
    HAVING SUM(SAL) >= 4000;
    
-- EXAM39-6
SELECT JOB AS 직업, SUM(SAL)
    FROM EMP
    WHERE JOB != 'SALESMAN'
    GROUP BY 직업
    HAVING SUM(SAL) >= 4000;