-- EXAM077
SELECT ENAME, SAL, (SELECT MAX(SAL) FROM EMP WHERE JOB = 'SALESMAN') AS 최대월급,
                   (SELECT MIN(SAL) FROM EMP WHERE JOB = 'SALESMAN') AS 최소월급
    FROM EMP
    WHERE JOB = 'SALESMAN';
    
-- EXAM078
INSERT  INTO EMP(EMPNO, ENAME,SAL, HIREDATE, JOB)
    VALUES(2812, 'JACK', 3500, TO_DATE('2019/06/05', 'RRRR/MM/DD'), 'ANLAYST');

-- EXAM079
UPDATE EMP
    SET SAL = 3200
    WHERE ENAME  = 'SCOTT';
    
-- EXAM080
DELETE FROM EMP
WHERE ENAME = 'SCOTT';

-- EXAM081
INSERT  INTO EMP(EMPNO, ENAME,SAL, DEPTNO)
    VALUES(1122, 'JACK', 3000, 20);

COMMIT;

UPDATE EMP
    SET SAL = 4000
    WHERE ENAME = 'SCOTT';
    
ROLLBACK;    

-- EXAM082
ALTER TABLE emp
   ADD loc varchar2(10);

MERGE INTO EMP E
USING DEPT D
ON (E.DEPTNO = D.DEPTNO)
WHEN MATCHED THEN
UPDATE SET E.LOC = D.LOC
WHEN NOT MATCHED THEN
INSERT (E.EMPNO, E.DEPTNO, E.LOC) VALUES (1111,D.DEPTNO, D.LOC);

-- EXAM083
UPDATE EMP
SET SAL = 3000
WHERE ENAME = 'JONES';

UPDATE EMP
SET SAL =  9000
WHERE ENAME = 'JONES';

COMMIT;

-- EXAM084
SELECT ENAME, SAL, DEPTNO
    FROM EMP
    WHERE ENAME = 'JONES'
    FOR UPDATE;
    
UPDATE EMP
SET SAL =  9000
WHERE ENAME = 'JONES';

COMMIT;

-- EXAM085
CREATE TABLE EMP2
AS
    SELECT *
        FROM EMP
        WHERE 1 = 2;

INSERT INTO EMP2(EMPNO, ENAME, SAL, DEPTNO)
SELECT EMPNO, ENAME, SAL, DEPTNO
    FROM EMP
    WHERE DEPTNO = 10;
    
-- EXAM086
UPDATE EMP
    SET SAL = (SELECT SAL
                FROM EMP
                WHERE ENAME = 'ALLEN')
WHERE JOB = 'SALESMAN';

-- EXAM087
DELETE FROM EMP
WHERE SAL > (SELECT SAL
                    FROM EMP
                    WHERE ENAME = 'SCOTT');
                    
-- EXAM087-2
DELETE FROM EMP M
WHERE SAL > (SELECT AVG(SAL)
                    FROM EMP S
                    WHERE S.DEPTNO = M.DEPTNO);

--EXAM088
ALTER TABLE DEPT
    ADD SUMSAL NUMBER(10);

MERGE INTO DEPT D
USING (SELECT DEPTNO, SUM(SAL) SUMSAL
            FROM EMP
            GROUP BY DEPTNO) V
ON (D.DEPTNO = V.DEPTNO)
WHEN MATCHED THEN
UPDATE SET D.SUMSAL =  V.SUMSAL;

-- EXAM089
SELECT RPAD(' ', LEVEL *  3) || ENAME AS EMPLOYEE, LEVEL, SAL, JOB
    FROM EMP
    START WITH ENAME  = 'KING'
    CONNECT BY PRIOR EMPNO = MGR;

-- EXAM090
SELECT RPAD(' ', LEVEL *  3) || ENAME AS EMPLOYEE, LEVEL, SAL, JOB
    FROM EMP
    START WITH ENAME  = 'KING'
    CONNECT BY PRIOR EMPNO = MGR AND ENAME != 'BLAKE';

-- EXAM091
SELECT RPAD(' ', LEVEL *  3) || ENAME AS EMPLOYEE, LEVEL, SAL, JOB
    FROM EMP
    START WITH ENAME  = 'KING'
    CONNECT BY PRIOR EMPNO = MGR
    ORDER SIBLINGS BY SAL DESC;
    
-- EXAM091-2
SELECT RPAD(' ', LEVEL *  3) || ENAME AS EMPLOYEE, LEVEL, SAL, JOB
    FROM EMP
    START WITH ENAME  = 'KING'
    CONNECT BY PRIOR EMPNO = MGR
    ORDER BY SAL DESC;

-- EXAM092
SELECT ENAME, SYS_CONNECT_BY_PATH(ENAME,  '/') AS PATH
    FROM EMP
    START WITH ENAME = 'KING'
    CONNECT BY PRIOR EMPNO = MGR;