-- EXAM056
SELECT ROWNUM, EMPNO, ENAME, JOB, SAL
    FROM EMP
    WHERE ROWNUM  <= 5;
    
-- EXAM057
SELECT EMPNO ENAME, JOB, SAL
    FROM EMP
    ORDER BY SAL DESC FETCH FIRST 4 ROWS ONLY;
    
-- EXAM057-2
SELECT EMPNO, ENAME, JOB, SAL
    FROM EMP
    ORDER BY SAL DESC
    FETCH FIRST 20 PERCENT ROWS ONLY;
    
-- EXAM057-3
SELECT EMPNO, ENAME, JOB, SAL
    FROM EMP
    ORDER BY SAL DESC
    FETCH FIRST 2 ROWS WITH TIES;
    
-- EXAM057-4
SELECT EMPNO, ENAME, JOB, SAL
    FROM EMP
    ORDER BY SAL DESC OFFSET 9 ROWS;

-- EXAM057-5
SELECT EMPNO, ENAME, JOB, SAL
    FROM EMP
    ORDER BY SAL DESC OFFSET 9 ROWS
    FETCH FIRST 2 ROWS ONLY;
    
-- EXAM058
SELECT ENAME, LOC
    FROM EMP, DEPT
    WHERE EMP.DEPTNO = DEPT.DEPTNO;

-- EXAM058-2
SELECT ENAME, LOC
    FROM EMP, DEPT;
    
-- EXAM058-3
SELECT ENAME, LOC
    FROM EMP, DEPT
    WHERE EMP.DEPTNO = DEPT.DEPTNO;
    
-- EXAM058-4
SELECT ENAME, LOC, JOB
    FROM EMP, DEPT
    WHERE EMP.DEPTNO = DEPT.DEPTNO AND EMP.JOB = 'ANALYST';
    
-- EXAM058-5
SELECT ENAME, LOC, JOB, DEPTNO
    FROM EMP, DEPT
    WHERE EMP.DEPTNO = DEPT.DEPTNO AND EMP.JOB = 'ANALYST';
    
-- EXAM058-6
SELECT ENAME, LOC, JOB, EMP.DEPTNO
    FROM EMP, DEPT
    WHERE EMP.DEPTNO = DEPT.DEPTNO AND EMP.JOB = 'ANALYST';

-- EXAM058-7
SELECT EMP.ENAME, DEPT.LOC, EMP.JOB, EMP.DEPTNO
    FROM EMP, DEPT
    WHERE EMP.DEPTNO = DEPT.DEPTNO AND EMP.JOB = 'ANALYST';

-- EXAM058-8
SELECT E.ENAME, D.LOC, E.JOB, E.DEPTNO
    FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO AND E.JOB = 'ANALYST';

-- EXAM058-9
SELECT EMP.ENAME, D.LOC, E.JOB, E.DEPTNO
    FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO AND E.JOB = 'ANALYST';

-- EXAM059
SELECT E.ENAME, E.SAL, S.GRADE
    FROM EMP E, SALGRADE S
    WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL;
    
-- EXAM059-2
SELECT * FROM SALGRADE;

-- EXAM059-3
SELECT E.ENAME, E.SAL, S.GRADE
    FROM EMP E, SALGRADE  S
    WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL;
    
 -- EXAM060
 SELECT E.ENAME,D.LOC
    FROM EMP E, DEPT D
    WHERE E.DEPTNO (+) = D.DEPTNO;
    
 -- EXAM061
 SELECT E.ENAME AS 사원, E.JOB AS 직업, M.ENAME AS 관리자, M.JOB AS 직업
    FROM EMP E, EMP M
    WHERE E.MGR = M.EMPNO AND E.JOB = 'SALSEMAN';


-- EXAM062
SELECT E.ENAME AS 이름, E.JOB AS 직업, E.SAL AS 월급, D.LOC AS 부서위치
    FROM EMP E  JOIN DEPT D
    ON (E.DEPTNO = D.DEPTNO)
    WHERE E.JOB = 'SALESMAN';
    
-- EXAM063
SELECT E.ENAME AS 이름, E.JOB AS 직업, E.SAL AS 월급, D.LOC AS 부서위치
    FROM EMP E JOIN DEPT D
    USING  (DEPTNO)
    WHERE E.JOB = 'SALESMAN';
    
-- EXAM064
SELECT E.ENAME AS 이름, E.JOB AS 직업, E.SAL AS 월급, D.LOC AS 부서위치
    FROM EMP E NATURAL JOIN DEPT D
    WHERE E.JOB = 'SALESMAN';
    
-- EXAM064-2
SELECT E.ENAME AS 이름, E.JOB AS 직업, E.SAL AS 월급, D.LOC AS 부서위치
    FROM EMP E NATURAL JOIN DEPT D
    WHERE E.JOB = 'SALESMAN' AND DEPTNO = 30;
    
-- EXAM065
SELECT E.ENAME AS 이름, E.JOB AS 직업, E.SAL AS 월급, D.LOC AS 부서위치
    FROM EMP E RIGHT OUTER JOIN DEPT D
    ON (E.DEPTNO = D.DEPTNO);
    
-- EXAM065-2
SELECT E.ENAME AS 이름, E.JOB AS 직업, E.SAL AS 월급, D.LOC AS 부서위치
    FROM EMP E LEFT OUTER JOIN DEPT D
    ON (E.DEPTNO = D.DEPTNO);
    
-- EXAM066
SELECT E.ENAME AS 이름, E.JOB AS 직업, E.SAL AS 월급, D.LOC AS 부서위치
    FROM EMP E FULL OUTER JOIN DEPT D
    ON (E.DEPTNO = D.DEPTNO);

-- EXAM066-2
SELECT E.ENAME AS 이름, E.JOB AS 직업, E.SAL AS 월급, D.LOC AS 부서위치
    FROM EMP E LEFT OUTER JOIN DEPT D
    ON (E.DEPTNO = D.DEPTNO)
UNION
SELECT E.ENAME AS 이름, E.JOB AS 직업, E.SAL AS 월급, D.LOC AS 부서위치
    FROM EMP E RIGHT OUTER JOIN DEPT D
    ON (E.DEPTNO = D.DEPTNO);

-- EXAM067
SELECT DEPTNO, SUM(SAL)
    FROM EMP
    GROUP BY DEPTNO
UNION ALL
    SELECT TO_NUMBER(NULL) AS DEPTNO, SUM(SAL)
    FROM EMP;

-- EXAM067-2
CREATE TABLE A (COL1 NUMBER(10));
CREATE TABLE B (COL1 NUMBER(10));
INSERT INTO A VALUES(1);
INSERT INTO A VALUES(2);
INSERT INTO A VALUES(3);
INSERT INTO A VALUES(4);
INSERT INTO A VALUES(5);

INSERT INTO B VALUES(3);
INSERT INTO B VALUES(4);
INSERT INTO B VALUES(5);
INSERT INTO B VALUES(6);
INSERT INTO B VALUES(7);

SELECT COL1 FROM A
UNION ALL
SELECT COL1 FROM B;
SELECT * FROM A;
DROP TABLE A;

-- EXAM068
SELECT DEPTNO, SUM(SAL)
    FROM EMP
    GROUP BY DEPTNO
UNION
SELECT NULL AS DEPTNO, SUM(SAL)
    FROM EMP;
    
-- EXAM068-2
CREATE TABLE C (COL1 NUMBER(10));
CREATE TABLE D (COL1 NUMBER(10));
INSERT INTO C VALUES(1);
INSERT INTO C VALUES(2);
INSERT INTO C VALUES(3);
INSERT INTO C VALUES(4);
INSERT INTO C VALUES(5);

INSERT INTO D VALUES(3);
INSERT INTO D VALUES(4);
INSERT INTO D VALUES(5);
INSERT INTO D VALUES(6);
INSERT INTO D VALUES(7);

SELECT COL1 FROM C
UNION
SELECT COL1 FROM D;
