-- EXAM069
SELECT ENAME, SAL, JOB, DEPTNO
    FROM EMP
    WHERE DEPTNO IN (10, 20)
INTERSECT
SELECT ENAME,SAL, JOB, DEPTNO
    FROM EMP
    WHERE DEPTNO IN (20,30);
    
-- EXAM069-2
CREATE TABLE E (COL1 NUMBER(10));
CREATE TABLE F (COL1 NUMBER(10));
INSERT INTO E VALUES(1);
INSERT INTO E VALUES(2);
INSERT INTO E VALUES(3);
INSERT INTO E VALUES(4);
INSERT INTO E VALUES(5);

INSERT INTO F VALUES(3);
INSERT INTO F VALUES(4);
INSERT INTO F VALUES(5);
INSERT INTO F VALUES(6);
INSERT INTO F VALUES(7);

SELECT COL1 FROM C
INTERSECT
SELECT COL1 FROM D;    

-- EXAM070
SELECT ENAME, SAL, JOB, DEPTNO
    FROM EMP
    WHERE DEPTNO IN (10, 20)
MINUS
SELECT ENAME,SAL, JOB, DEPTNO
    FROM EMP
    WHERE DEPTNO IN (20,30);

-- EXAM070-2
CREATE TABLE G (COL1 NUMBER(10));
CREATE TABLE H (COL1 NUMBER(10));
INSERT INTO G VALUES(1);
INSERT INTO G VALUES(2);
INSERT INTO G VALUES(3);
INSERT INTO G VALUES(4);
INSERT INTO G VALUES(5);

INSERT INTO H VALUES(3);
INSERT INTO H VALUES(4);
INSERT INTO H VALUES(5);
INSERT INTO H VALUES(6);
INSERT INTO H VALUES(7);

SELECT COL1 FROM G
MINUS
SELECT COL1 FROM H;

-- EXAM071
SELECT ENAME, SAL
    FROM EMP
    WHERE SAL > (SELECT SAL
                    FROM EMP
                    WHERE ENAME= 'JONES');
                    
-- EXAM072
SELECT ENAME, SAL
    FROM EMP
    WHERE SAL IN (SELECT SAL
                    FROM EMP
                    WHERE JOB= 'SALESMAN');
                    
-- EXAM073
SELECT ENAME, SAL
    FROM EMP
    WHERE EMPNO NOT IN (SELECT MGR
                            FROM EMP
                            WHERE MGR IS NOT NULL);
                            
-- EXAM074
SELECT *
    FROM DEPT D
    WHERE EXISTS (SELECT *
                    FROM EMP E
                    WHERE E.DEPTNO= D.DEPTNO);
                                                
-- EXAM074-2
SELECT *
    FROM DEPT D
    WHERE NOT EXISTS (SELECT *
                        FROM EMP E
                        WHERE E.DEPTNO= D.DEPTNO);
                        
-- EXAM075
SELECT JOB, SUM(SAL)
    FROM EMP
    GROUP BY JOB
    HAVING SUM(SAL)> (SELECT SUM(SAL)
                        FROM EMP
                        WHERE JOB = 'SALESMAN');
                        
-- EXA076
SELECT V.ENAME, V.SAL, V.순위
    FROM (SELECT ENAME, SAL, RANK() OVER (ORDER BY SAL DESC) 순위
            FROM EMP) V
    WHERE V.순위= 1;

                    