-- EXAM040
SELECT COUNT(EMPNO)
    FROM EMP;
    
-- EXAM040-2
SELECT COUNT(COMM)
    FROM EMP;
    
-- EXAM041
SELECT ENAME, JOB, SAL, RANK() OVER (ORDER BY SAL DESC) 순위
    FROM EMP
    WHERE JOB IN ('ANALYST', 'MANAGER');
    
-- EXAM041-2
SELECT ENAME, JOB, SAL, RANK() OVER (PARTITION BY JOB ORDER BY SAL DESC) 순위
    FROM EMP;

-- EXAM042
SELECT ENAME, JOB, SAL, RANK() OVER ( ORDER BY SAL DESC) AS RANK, DENSE_RANK() OVER (ORDER BY SAL DESC) AS DENSE_RANK
    FROM EMP
    WHERE JOB IN ('ANALYST', 'MANAGER');
    
-- EXAM042-2
SELECT JOB, ENAME, SAL, DENSE_RANK() OVER (PARTITION BY JOB ORDER BY SAL DESC) 순위
    FROM EMP
    WHERE HIREDATE BETWEEN TO_DATE('1981/01/01', 'RRRR/MM/DD') AND TO_DATE('1981/12/31', 'RRRR/MM/DD');
    
-- EXAM042-3
SELECT DENSE_RANK(2975) WITHIN GROUP (ORDER BY SAL DESC) 순위
    FROM EMP;
    
-- EXAM042-4
SELECT DENSE_RANK('81/11/17') WITHIN GROUP (ORDER BY HIREDATE ASC) 순위
    FROM EMP;
    
-- EXAM043
SELECT ENAME, JOB, SAL, NTILE(4) OVER (ORDER BY SAL DESC NULLS LAST) 등급
    FROM EMP
    WHERE JOB IN ('ANALYST', 'MANAGER', 'CLERK');
    
-- EXAM044
SELECT ENAME, SAL, RANK() OVER (ORDER BY SAL DESC) AS RANK,
                    DENSE_RANK() OVER (ORDER BY SAL DESC) AS DENSE_RANK,
                    CUME_DIST() OVER (ORDER BY SAL DESC) AS CUM_DIST
    FROM EMP;
    
-- EXAM044-2
SELECT JOB, ENAME, SAL, RANK() OVER (PARTITION BY JOB ORDER BY SAL DESC) AS RANK,
                        CUME_DIST() OVER (PARTITION BY JOB ORDER BY SAL DESC) AS CUM_DIST
    FROM EMP;
    
-- EXAM045
SELECT DEPTNO, LISTAGG(ENAME, ',') WITHIN GROUP (ORDER BY ENAME) AS EMPLOYEE
    FROM EMP
    GROUP BY DEPTNO;
    
-- EXAM045-2
SELECT JOB, LISTAGG(ENAME, ',') WITHIN GROUP (ORDER BY ENAME ASC) AS EMPLOYEE
    FROM EMP
    GROUP BY JOB;
    
-- EXAM045-3
SELECT JOB, LISTAGG(ENAME || '('||SAL||')', ',') WITHIN GROUP (ORDER BY ENAME ASC) AS EMPLOYEE
    FROM EMP
    GROUP BY JOB;
    
-- EXAM046
SELECT EMPNO, ENAME, SAL,
        LAG(SAL, 1) OVER (ORDER BY SAL ASC) "전 행",
        LEAD(SAL, 1) OVER (ORDER BY SAL ASC) "다음 행"
    FROM EMP
    WHERE JOB IN ('ANALYST', 'MANAGER');
    
-- EXAM046-2
SELECT EMPNO, ENAME, HIREDATE,
        LAG(HIREDATE, 1) OVER (ORDER BY HIREDATE ASC) "전 행",
        LEAD(HIREDATE, 1) OVER (ORDER BY HIREDATE ASC) "다음 행"
    FROM EMP
    WHERE JOB IN ('ANALYST', 'MANAGER');
    
-- EXAM046-3
SELECT DEPTNO, EMPNO, ENAME, HIREDATE,
        LAG(HIREDATE, 1) OVER (PARTITION BY DEPTNO ORDER BY HIREDATE ASC) "전 행",
        LEAD(HIREDATE, 1) OVER (PARTITION BY DEPTNO ORDER BY HIREDATE ASC) "다음 행"
    FROM EMP
    WHERE JOB IN ('ANALYST', 'MANAGER');

-- EXAM047
SELECT SUM(DECODE(DEPTNO, 10, SAL)) AS "10",
       SUM(DECODE(DEPTNO, 20, SAL)) AS "20",
       SUM(DECODE(DEPTNO, 30, SAL)) AS "30"
    FROM EMP;
    
-- EXAM047-2
SELECT DEPTNO, DECODE(DEPTNO, 10, SAL) AS "10"
    FROM EMP;
    
-- EXAM047-3
SELECT SUM(DECODE(DEPTNO, 10, SAL)) AS "10"
    FROM EMP;

-- EXAM047-4
SELECT SUM(DECODE(DEPTNO, 10, SAL)) AS "10",
        SUM(DECODE(DEPTNO, 20, SAL)) AS "20",
        SUM(DECODE(DEPTNO, 30, SAL)) AS "30"
    FROM EMP;
    
-- EXAM047-5
SELECT SUM(DECODE(JOB, 'ANALYST', SAL)) AS "ANALYST",
        SUM(DECODE(JOB, 'CLERK', SAL)) AS "CLERK",
        SUM(DECODE(JOB, 'MANAGER', SAL)) AS "MANAGER",
        SUM(DECODE(JOB, 'SALESMAN', SAL)) AS "SALESMAN"
    FROM EMP;

-- EXAM047-6
SELECT SUM(DECODE(JOB, 'ANALYST', SAL)) AS "ANALYST",
        SUM(DECODE(JOB, 'CLERK', SAL)) AS "CLERK",
        SUM(DECODE(JOB, 'MANAGER', SAL)) AS "MANAGER",
        SUM(DECODE(JOB, 'SALESMAN', SAL)) AS "SALESMAN"
    FROM EMP
    GROUP BY DEPTNO;
    
-- EXAM048
SELECT * 
    FROM (SELECT DEPTNO, SAL FROM EMP)
    PIVOT (SUM(SAL) FOR DEPTNO IN (10, 20, 30));
    
-- EXAM048-2
SELECT * 
    FROM (SELECT JOB, SAL FROM EMP)
    PIVOT (SUM(SAL) FOR JOB IN ('ANALYST', 'CLERK', 'MANAGER', 'SALESMAN'));
    
-- EXAM048-3
SELECT * 
    FROM (SELECT JOB, SAL FROM EMP)
    PIVOT (SUM(SAL) FOR JOB IN ('ANALYST' AS "ANALYST", 'CLERK' AS "CLERK", 'MANAGER' AS "MANAGER", 'SALESMAN' AS "SALESMAN"));
    
-- EXAM049
drop  table order2;

create table order2
( ename  varchar2(10),
  bicycle  number(10),
  camera   number(10),
  notebook  number(10) );

insert  into  order2  values('SMITH', 2,3,1);
insert  into  order2  values('ALLEN',1,2,3 );
insert  into  order2  values('KING',3,2,2 );

commit;


SELECT *
    FROM ORDER2
    UNPIVOT (건수 FOR 아이템 IN (BICYCLE, CAMERA, NOTEBOOK));

-- EXAM049-2
SELECT *
    FROM ORDER2
    UNPIVOT (건수 FOR 아이템 IN (BICYCLE AS 'B', CAMERA AS 'C', NOTEBOOK AS 'N'));

-- EXAM049-3
SELECT *
    FROM ORDER2
    UNPIVOT INCLUDE NULLS (건수 FOR 아이템 IN (BICYCLE AS 'B', CAMERA AS 'C', NOTEBOOK AS 'N'));

-- EXAM050
SELECT EMPNO, ENAME, SAL, SUM(SAL) OVER (ORDER BY EMPNO ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) 누적치
    FROM EMP
    WHERE JOB IN ('ANLAYST', 'MANAGER');
    
-- EXAM051
SELECT EMPNO, ENAME, SAL, RATIO_TO_REPORT(SAL) OVER () AS 비율
    FROM EMP
    WHERE DEPTNO = 20;

-- EXAM051-2
SELECT EMPNO, ENAME, SAL, RATIO_TO_REPORT(SAL) OVER () AS 비율, SAL/SUM(SAL) OVER () AS "비교 비율"
    FROM EMP
    WHERE DEPTNO = 20;


-- EXAM052
SELECT JOB, SUM(SAL)
    FROM EMP
    GROUP BY ROLLUP(JOB);
    
-- EXAM052-2
SELECT DEPTNO, JOB, SUM(SAL)
    FROM EMP
    GROUP BY ROLLUP(DEPTNO, JOB);
    
-- EXAM053
SELECT JOB, SUM(SAL)
    FROM EMP
    GROUP BY CUBE(JOB);

-- EXAM053-2
SELECT DEPTNO, JOB, SUM(SAL)
    FROM EMP
    GROUP BY CUBE(DEPTNO, JOB);

-- EXAM054
SELECT DEPTNO, JOB, SUM(SAL)
    FROM EMP
    GROUP BY GROUPING SETS((DEPTNO), (JOB), ());

-- EXAM055
SELECT EMPNO, ENAME, SAL, RANK() OVER (ORDER BY SAL DESC) RANK,
                            DENSE_RANK() OVER (ORDER BY SAL DESC) DENSE_RANK,
                            ROW_NUMBER() OVER (ORDER BY SAL DESC) 번호
    FROM EMP
    WHERE DEPTNO = 20;
    
-- EXAM055-2
SELECT EMPNO, ENAME, SAL, ROW_NUMBER() OVER () 번호
    FROM EMP
    WHERE DEPTNO = 20;
    
-- EXAM055-3
SELECT EMPNO, ENAME, SAL, ROW_NUMBER() OVER (PARTITION BY DEPTNO ORDER BY SAL DESC) 번호
    FROM EMP
    WHERE DEPTNO IN (10, 20);
    