-- EXAM001
SELECT EMPNO, ENAME, SAL
    FROM EMP;
  
-- EXAM002
SELECT * FROM EMP;

-- EXAM002-2
SELECT EMPNO, ENAME, job, MGR, HIREDATE, SAL, COMM, DEPTNO
    FROM EMP;
  
-- EXAM003
SELECT EMPNO as 사원번호, ENAME as 사원이름, SAL as "Salary"
    FROM EMP;
  
-- NOTE
SELECT ENAME, SAL * (12 + 3000)
    FROM EMP;

SELECT ENAME, SAL * (12 + 3000) as 월급
    FROM EMP;  

SELECT ENAME, SAL * (12 + 3000) as 월급
    FROM EMP
    ORDER BY 월급 DESC;
    
-- EXAM004
SELECT ENAME || SAL
    FROM EMP;
    
-- EXAM004-2
SELECT ENAME || '의 월급은' || SAL || '입니다 ' as 월급정보
    FROM EMP;
    
-- EXAM004-3
SELECT ENAME || '의 직업은' || JOB || '입니다 ' as 직업정보
    FROM EMP;
    
-- EXAM005    
SELECT DISTINCT JOB
    FROM EMP;
    
-- EXAM005-2    
SELECT UNIQUE JOB
    FROM EMP;

-- EXAM006
SELECT ENAME, SAL
    FROM EMP
    ORDER BY SAL ASC;

-- EXAM006-2
SELECT ENAME, SAL AS 월급
    FROM EMP
    ORDER BY 월급 ASC;
    
-- EXAM006-3
SELECT ENAME, DEPTNO, SAL
    FROM EMP
    ORDER BY DEPTNO ASC, SAL DESC;
    
-- EXAM006-4
SELECT ENAME, DEPTNO, SAL
    FROM EMP
    ORDER BY 2 ASC, 3 DESC;

-- EXAM007
SELECT ENAME, SAL, JOB
    FROM EMP
    WHERE SAL = 3000;
    
-- EXAM007-2
SELECT ENAME AS 이름, SAL AS 월급
    FROM EMP
    WHERE SAL >= 3000;
    
-- EXAM007-3
SELECT ENAME AS 이름, SAL AS 월급
    FROM EMP
    WHERE 월급 >= 3000;
    
-- EXAM008
SELECT ENAME, SAL, JOB HIREDATE, DEPTNO
    FROM EMP
    WHERE ENAME = 'SCOTT';
    
-- EXAM008-2
SELECT ENAME, HIREDATE
    FROM EMP
    WHERE HIREDATE = '81/11/17';
    
-- EXAM008-3
SELECT *
    FROM NLS_SESSION_PARAMETERS
    WHERE PARAMETER = 'NLS_DATE_FORMAT';
    
-- EXAM008-4
ALTER SESSION SET NLS_DATE_FORMAT = 'YY/MM/DD';

-- EXAM008-5
SELECT ENAME, HIREDATE
    FROM EMP
    WHERE HIREDATE = '81/11/17';
    
-- EXAM008-6
ALTER SESSION SET NLS_DATE_FORMAT = 'RR/MM/DD';

-- EXAM009
SELECT ENAME, SAL * 12 AS 연봉
    FROM EMP
    WHERE SAL * 12 >= 36000;
    
-- EXAM009-2
SELECT ENAME, SAL, COMM, SAL + COMM
    FROM EMP
    WHERE DEPTNO = 10;
    
-- NOTE
SELECT SAL + COMM
    FROM EMP
    WHERE ENAME = 'KING';
    
SELECT SAL + NVL(COMM, 0)
    FROM EMP
    WHERE ENAME = 'KING';    
    
-- EXAM010
SELECT ENAME, SAL, JOB, DEPTNO
    FROM EMP
    WHERE SAL <= 1200;
    
-- EXAM011
SELECT ENAME, SAL
    FROM EMP
    WHERE SAL BETWEEN 1000 AND 3000;
    
-- EXAM011-2
SELECT ENAME, SAL
    FROM EMP
    WHERE (SAL >= 1000 AND SAL <= 3000);
    
-- NOTE
SELECT ENAME, SAL
    FROM EMP
    WHERE SAL BETWEEN 1000 AND 3000;

SELECT ENAME, SAL
    FROM EMP
    WHERE SAL BETWEEN 3000 AND 1000;    

-- EXAM011-3
SELECT ENAME, SAL
    FROM EMP
    WHERE SAL NOT BETWEEN 1000 AND 3000; 
    
-- EXAM011-4
SELECT ENAME, SAL
    FROM EMP
    WHERE (SAL < 1000 OR SAL > 3000);
    
-- EXAM011-5
SELECT ENAME, HIREDATE
    FROM EMP
    WHERE HIREDATE BETWEEN '1982/01/01' AND '1982/12/31';
    
-- EXAM012
SELECT ENAME, SAL
    FROM EMP
    WHERE ENAME LIKE 'S%';
    
-- EXAM012-2
SELECT ENAME
    FROM EMP
    WHERE ENAME LIKE '_M%';
    
-- EXAM012-3
SELECT ENAME
    FROM EMP
    WHERE ENAME LIKE '%T';
    
-- EXAM012-4
SELECT ENAME
    FROM EMP
    WHERE ENAME LIKE '%A%';
    
-- EXAM013
SELECT ENAME, COMM
    FROM EMP
    WHERE COMM IS NULL;
    
-- EXAM014
SELECT ENAME, SAL, JOB
    FROM EMP
    WHERE JOB IN ('SALESMAN', 'ANALYST', 'MANAGER');
    
-- EXAM014-2
SELECT ENAME, SAL, JOB
    FROM EMP
    WHERE (JOB = 'SALESMAN' OR JOB = 'ANALYST' OR JOB = 'MANAGER');
    
-- EXAM014-3
SELECT ENAME SAL, JOB
    FROM EMP
    WHERE JOB NOT IN ('SALESMAN', 'ANALYST', 'MANAGER');

-- EXAM014-4
SELECT ENAME, SAL, JOB
    FROM EMP
    WHERE (JOB != 'SALESMAN' AND JOB != 'ANALYST' AND JOB != 'MANAGER');
    
 -- EXAM015
 SELECT ENAME, SAL, JOB
    FROM EMP
    WHERE JOB = 'SALESMAN' AND SAL >= 1200;
    
-- EXAM015
SELECT ENAME, SAL, JOB
    FROM EMP
    WHERE JOB = 'ABCDEFG' AND SAL >= 1200;
    